{% set name = "inertia-django" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inertia_django-{{ version }}.tar.gz
  sha256: b31cf7190630a4e75057d8a236309e33f9fa988a0a22f5ea94cd8e53887dda8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - django >=4.0.0,<5.0.0
    - requests >=2.0.0,<3.0.0

test:
  imports:
    - inertia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/inertiajs/inertia-django
  summary: Django adapter for the InertiaJS framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
