{% set name = "inertia-django" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inertia_django-{{ version }}.tar.gz
  sha256: 36511038caf2cbb6f54a08f17dc18fe1dd1b30c712a616672704e395b984f250

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=4
    - requests >=2.0.0,<3.0.0

test:
  imports:
    - inertia
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/inertiajs/inertia-django
  summary: Django adapter for the InertiaJS framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
